### ISSUE TITLE
[Question] What is preventing this from running on terraform 0.11?

### ISSUE THREAD

**Issue by kceb** [nrkno/terraform-provider-lastpass#14]
Hello, I currently am on terraform 0.11 and we haven't had the chance to update, but I'd love to use your provider. I was wondering if there's a strict requirement to be on 0.12. I would assume that provider code (which here is written in Go) is not dependent on terraform versions. However, I haven't written a provider so I could be wrong/misguided. Thanks

**Comment by martensson** [comment]
Hi @kceb! Sorry for the delay to answer, but you are correct that it might work just fine with v0.11. But it has only been tested on our side from version 0.12.0 and above.

The config examples will break in previous versions thought (see: https://www.terraform.io/upgrade-guides/0-12.html#upgrading-terraform-configuration). If you keep the old syntax it will probably work just fine thought.

I should probably update the README to better reflect it 👍 

Thanks for letting me know!
