### ISSUE TITLE
How to set a folder name while creating a credentials?

### ISSUE THREAD

**Issue by kaushik-xs** [nrkno/terraform-provider-lastpass#21]
I have organised my password into folders. How to set the name of the folder while creating a credential?

<img width="808" alt="Screenshot 2020-05-17 at 11 45 12 AM" src="https://user-images.githubusercontent.com/57823802/82137260-09e5d500-9834-11ea-83db-9c98ef217498.png">

**Comment by martensson** [comment]
Hi @kaushik-xs, 
This is set in the name:

```
resource "lastpass_secret" "mysecret" {
    name = "some dir/test123"
    username = "foo"
    password = "test123"
    note = <<EOF
ABC
DEF
EOF
}
```
