### ISSUE TITLE
Terraform registry?

### ISSUE THREAD

**Issue by imphil** [nrkno/terraform-provider-lastpass#24]
Thanks for this nice terraform plugin.

This might be a stupid question, but would it be possible to add this provider to the Terraform Registry, to make it installable through `terraform init`? (I might be missing something obvious which makes that impossible, of course.)

**Comment by midacts** [comment]
there's usually a process to get added to the TF registry.

https://www.terraform.io/guides/terraform-provider-development-program.html

usually looks something like this:
https://github.com/microsoft/terraform-provider-azuredevops/issues/241

**Comment by martensson** [comment]
Hi guys, this is currently one of the new things supported in Terraform v0.13 Beta. I have also requested this feature for over a year and glad that it is finally being supported.

I am working on it and hope to have it ready once 0.13 is released. 👍

**Comment by martensson** [comment]
This is now resolved (see updated README and release) 👍
