### ISSUE TITLE
How to debug an error running terraform apply

### ISSUE THREAD

**Issue by MoogyG** [nrkno/terraform-provider-lastpass#36]
I get this error : 
```
Error: 

  on main.tf line 173, in resource "lastpass_secret" "mysecret":
 173: resource "lastpass_secret" "mysecret" {
```
while running `terraform apply` with a script containing this : 
```
provider "lastpass" {
  username = var.lastpass_username
  password = var.lastpass_password
}

resource "lastpass_secret" "mysecret" {
  name = "My site"
}
```

I have no more informations while using TF_LOG="TRACE".
I am using Terraform Cloud 0.13.4 with terraform-provider-lastpass 0.5.1.
If I comment the block above, my script runs correctly

Any idea? How to add debug?

Thanks

**Comment by martensson** [comment]
Hi @MoogyG! I am sorry for the delay, but the provider has been updated to 0.5.2 with some improvements, also to logging. Please run another test and let me know if you still got problems.
Kindly,
Benjamin

**Comment by MoogyG** [comment]
It was my bad, I didn't install `lastpass-cli` in my [terraform container](https://hub.docker.com/r/hashicorp/terraform/). After that it works great!
Thanks @martensson
