### ISSUE TITLE
Warning: Provider source not supported in Terraform v0.12

### ISSUE THREAD

**Issue by juergenschubert** [nrkno/terraform-provider-lastpass#37]
```
terraform {
  required_providers {
    lastpass = {
      source = "nrkno/lastpass"
    }
  }
}
```
Warning: Provider source not supported in Terraform v0.12  
  on provider lastpass.tf line 3, in terraform:  
   3:     lastpass = {
   4:       source = "nrkno/lastpass"
   5:     }

A source was declared for provider lastpass. Terraform v0.12 does not support
the provider source attribute. It will be ignored.

**Comment by juergenschubert** [comment]
provider "lastpass" {
  version  = "0.5.0"
  username = "login"
  password = "password"
  #    password = file("${path.module}/.lpass")
}


terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "lastpass" not available for installation.

A provider named "lastpass" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

- Downloading plugin for provider "aws" (hashicorp/aws) 3.12.0...

Error: no provider exists with the given name

**Comment by juergenschubert** [comment]
terraform providers
.
├── provider.aws
├── provider.lastpass 0.5.0
└── provider.vsphere

**Comment by imphil** [comment]
Before terraform 0.13 you had to manually install the plugin; this isn't necessary any more with 0.13+, and the docs only apply to 0.13+. I'd suggest updating to 0.13+, it will make your life much easier.

**Comment by martensson** [comment]
@juergenschubert as @imphil mentioned the doc is assuming you are running Terraform 0.13+. A lot of things have changed and I recommend that you update your config to support it. The provider will still work on older versions if you install it manually using the old syntax thought. But you might be stuck with an older version if you do so unfortunately.
