### ISSUE TITLE
Manage share folders and permissions

### ISSUE THREAD

**Issue by copolycube** [nrkno/terraform-provider-lastpass#38]
Lastpass cli is able to create and manage permissions on shared folders, which allow for sharing content with multiple users.

**Comment by martensson** [comment]
Hi @copolycube this is a bit outside the scope of this provider, and not something we have planned for now. The lpass/lastpass-cli project is also a bit abandoned it seems, so we are trying to see if there are any alternatives. This also means that we do not want to be too dependent on the lastpass-cli until we know for sure that there is no better API to use.
But the idea is interesting and definitely something we will keep in mind!

**Comment by copolycube** [comment]
Thanks for your answer ! Which Lastpass API are you using on the background of this provider ?
